name: Release

on:
  release:
    types: [published]
      
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
      
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
    
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Restore
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal
          
      - name: Pack
        run: dotnet pack -c Release -o ./out --no-restore --no-build 

      - name: Push package - local
        run: |
          dotnet nuget push ./out/*.nupkg \
          -s https://nuget.pkg.github.com/Byteology/index.json -k ${{ secrets.GITHUB_TOKEN }} \
          --skip-duplicate --no-symbols true

      - name: Push package - NuGet.org
        run: |
          dotnet nuget push ./out/*.nupkg \
          -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }} \
          --skip-duplicate --no-symbols true
